
DROP TABLE IF EXISTS workObjectV3 CASCADE;
DROP TABLE IF EXISTS workContainsV3 CASCADE;
DROP TABLE IF EXISTS cacheV3 CASCADE;

DROP VIEW IF EXISTS workContains;
DROP VIEW IF EXISTS workObject;
CREATE VIEW workContains AS SELECT * FROM workContainsV4;
CREATE VIEW workObject AS SELECT * FROM workObjectV4;
